const $=(s)=>document.querySelector(s);let current=null,currentJobKey='';
async function req(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},credentials:'same-origin',...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
function text(id,v){const e=document.getElementById(id);if(e)e.textContent=v;}
function toast(msg,error=false){const e=$('#toast');e.textContent=msg;e.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='toast',3200);}
function showLogin(){$('#loginView').classList.remove('hidden');$('#adminView').classList.add('hidden');$('#logoutBtn').classList.add('hidden');}
function showAdmin(){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');refreshAll();}
async function checkSession(){try{const s=await req('/api/admin/session');s.authenticated?showAdmin():showLogin();}catch{showLogin();}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();text('loginError','');try{await req('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';showAdmin();}catch(err){text('loginError',err.message);}});
$('#logoutBtn').addEventListener('click',async()=>{try{await req('/api/admin/logout',{method:'POST',body:'{}'});}catch{}showLogin();});
function formatUptime(seconds){if(!Number.isFinite(Number(seconds)))return '—';const s=Number(seconds),d=Math.floor(s/86400),h=Math.floor(s/3600)%24,m=Math.floor(s/60)%60;return d?`${d}d ${h}h ${m}m`:`${h}h ${m}m`;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderPlayers(players=[]){const body=$('#playersTable');if(!players.length){body.innerHTML='<tr><td colspan="8" class="empty">Keine Spieler online oder REST API nicht verbunden.</td></tr>';return;}body.innerHTML=players.map(p=>`<tr><td><strong>${esc(p.name||'Unbekannt')}</strong></td><td>${esc(p.accountName||'—')}</td><td><code>${esc(p.userId||'—')}</code></td><td><code>${esc(p.playerId||'—')}</code></td><td>${p.level??'—'}</td><td>${p.ping==null?'—':`${Math.round(Number(p.ping))} ms`}</td><td>${Math.round(Number(p.location_x)||0)}, ${Math.round(Number(p.location_y)||0)}</td><td>${p.building_count??'—'}</td></tr>`).join('');}
function renderStatus(data){current=data;const s=data.server,live=data.live||{},info=live.info||{},metrics=live.metrics||{};text('serverState',s.running?'ONLINE':'OFFLINE');text('serverName',info.servername||s.serverPath);text('steamState',s.steamcmdInstalled?'INSTALLIERT':'FEHLT');text('pidState',s.pid||'—');text('playerCount',metrics.currentplayernum??(live.players?.length??'—'));text('playerSlots',`von ${metrics.maxplayernum??data.palworld.maxPlayers??32} Slots`);text('serverFps',metrics.serverfps==null?'—':Math.round(Number(metrics.serverfps)));text('frameTime',metrics.serverframetime==null?'—':`${Number(metrics.serverframetime).toFixed(1)} ms Frametime`);text('gameVersion',info.version||'—');text('gameUptime',formatUptime(metrics.uptime));text('restState',data.rest.connected?'LIVE':data.rest.configured?'OFFLINE':'NICHT EINGERICHTET');text('restHint',data.rest.error||`Port ${data.palworld.rest?.port||8212}`);text('playersUpdated',live.updatedAt?new Date(live.updatedAt).toLocaleTimeString('de-DE'):'—');renderPlayers(live.players||[]);const pill=$('#serverPill');pill.className=`pill ${s.running?'online':'offline'}`;text('serverPillText',s.running?'Server online':'Server offline');$('#installBox').classList.toggle('hidden',s.installed);$('#restBox').classList.toggle('hidden',data.rest.configured&&data.rest.connected);document.querySelectorAll('[data-action="start"]').forEach(b=>b.disabled=!s.installed||s.running||data.job?.running);document.querySelectorAll('[data-action="stop"]').forEach(b=>b.disabled=!s.running||data.job?.running);document.querySelectorAll('[data-action="restart"]').forEach(b=>b.disabled=!s.running||data.job?.running);document.querySelectorAll('[data-action="update"]').forEach(b=>b.disabled=!s.installed||s.running||data.job?.running);$('#installBtn').disabled=!!data.job?.running;$('#restSetupBtn').disabled=!s.installed;}
async function refreshStatus(){try{renderStatus(await req('/api/admin/status'));}catch(err){if(/angemeldet/i.test(err.message))showLogin();}}
async function refreshJob(){try{const {job}=await req('/api/admin/job');const badge=$('#jobBadge');if(!job){badge.textContent='IDLE';badge.className='job-badge';return;}const key=`${job.type}:${job.running}:${job.finishedAt||''}:${job.log?.length||0}`;if(key!==currentJobKey){currentJobKey=key;$('#jobLog').textContent=(job.log||[]).join('\n')||`${job.type} läuft…`;$('#jobLog').scrollTop=$('#jobLog').scrollHeight;}badge.textContent=job.running?'LÄUFT':job.success?'ERFOLGREICH':'FEHLER';badge.className=`job-badge ${job.running?'running':job.success?'ok':'fail'}`;}catch{}}
async function action(name){try{await req(`/api/admin/server/${name}`,{method:'POST',body:'{}'});toast({start:'Server wird gestartet…',stop:'Server wird gestoppt…',restart:'Server wird neu gestartet…',update:'Update gestartet.'}[name]||'Aktion ausgeführt.');await refreshAll();}catch(err){toast(err.message,true);}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));
$('#installBtn').addEventListener('click',async()=>{if(!confirm('SteamCMD und Palworld Dedicated Server automatisch installieren?'))return;try{await req('/api/admin/server/install',{method:'POST',body:'{}'});toast('Installation gestartet.');await refreshAll();}catch(err){toast(err.message,true);}});
$('#restSetupBtn').addEventListener('click',async()=>{const running=current?.server?.running;if(!confirm(`Palworld REST API jetzt lokal einrichten?${running?' Der laufende Gameserver wird dafür einmal neu gestartet.':''}`))return;try{const r=await req('/api/admin/rest/setup',{method:'POST',body:'{}'});toast(r.restarted?'REST eingerichtet, Server wurde neu gestartet.':'REST eingerichtet. Starte den Server, um Live-Daten zu erhalten.');setTimeout(refreshAll,2500);}catch(err){toast(err.message,true);}});
async function refreshAll(){await Promise.all([refreshStatus(),refreshJob()]);}
setInterval(()=>!$('#adminView').classList.contains('hidden')&&refreshStatus(),4000);setInterval(()=>!$('#adminView').classList.contains('hidden')&&refreshJob(),1500);checkSession();
