const $=(s)=>document.querySelector(s);let current=null,currentJobKey='';
async function req(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},credentials:'same-origin',...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
function text(id,v){const e=document.getElementById(id);if(e)e.textContent=v;}
function toast(msg,error=false){const e=$('#toast');e.textContent=msg;e.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='toast',3200);}
function showLogin(){ $('#loginView').classList.remove('hidden');$('#adminView').classList.add('hidden');$('#logoutBtn').classList.add('hidden'); }
function showAdmin(){ $('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');refreshAll(); }
async function checkSession(){try{const s=await req('/api/admin/session');s.authenticated?showAdmin():showLogin();}catch{showLogin();}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();text('loginError','');try{await req('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';showAdmin();}catch(err){text('loginError',err.message);}});
$('#logoutBtn').addEventListener('click',async()=>{try{await req('/api/admin/logout',{method:'POST',body:'{}'});}catch{}showLogin();});
function renderStatus(data){current=data;const s=data.server;text('serverState',s.running?'ONLINE':'OFFLINE');text('installState',s.installed?'INSTALLIERT':'FEHLT');text('steamState',s.steamcmdInstalled?'INSTALLIERT':'FEHLT');text('serverPath',s.serverPath);text('pidState',s.pid||'—');text('processState',s.running?(s.processName||'Läuft'):'Gestoppt');const pill=$('#serverPill');pill.className=`pill ${s.running?'online':'offline'}`;text('serverPillText',s.running?'Server online':'Server offline');$('#installBox').classList.toggle('hidden',s.installed);document.querySelectorAll('[data-action="start"]').forEach(b=>b.disabled=!s.installed||s.running||data.job?.running);document.querySelectorAll('[data-action="stop"]').forEach(b=>b.disabled=!s.running||data.job?.running);document.querySelectorAll('[data-action="restart"]').forEach(b=>b.disabled=!s.running||data.job?.running);document.querySelectorAll('[data-action="update"]').forEach(b=>b.disabled=!s.installed||s.running||data.job?.running);$('#installBtn').disabled=!!data.job?.running;}
async function refreshStatus(){try{renderStatus(await req('/api/admin/status'));}catch(err){if(/angemeldet/i.test(err.message))showLogin();}}
async function refreshJob(){try{const {job}=await req('/api/admin/job');const badge=$('#jobBadge');if(!job){badge.textContent='IDLE';badge.className='job-badge';return;}const key=`${job.type}:${job.running}:${job.finishedAt||''}:${job.log?.length||0}`;if(key!==currentJobKey){currentJobKey=key;$('#jobLog').textContent=(job.log||[]).join('\n')||`${job.type} läuft…`;$('#jobLog').scrollTop=$('#jobLog').scrollHeight;}badge.textContent=job.running?'LÄUFT':job.success?'ERFOLGREICH':'FEHLER';badge.className=`job-badge ${job.running?'running':job.success?'ok':'fail'}`;}catch{}}
async function action(name){try{await req(`/api/admin/server/${name}`,{method:'POST',body:'{}'});toast({start:'Server wird gestartet…',stop:'Server wird gestoppt…',restart:'Server wird neu gestartet…',update:'Update gestartet.'}[name]||'Aktion ausgeführt.');await refreshAll();}catch(err){toast(err.message,true);}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));
$('#installBtn').addEventListener('click',async()=>{if(!confirm('SteamCMD und Palworld Dedicated Server automatisch installieren?'))return;try{await req('/api/admin/server/install',{method:'POST',body:'{}'});toast('Installation gestartet.');await refreshAll();}catch(err){toast(err.message,true);}});
async function refreshAll(){await Promise.all([refreshStatus(),refreshJob()]);}
setInterval(()=>!$('#adminView').classList.contains('hidden')&&refreshStatus(),4000);setInterval(()=>!$('#adminView').classList.contains('hidden')&&refreshJob(),1500);checkSession();
