(() => {
  const $=id=>document.getElementById(id);
  let loading=false,lastLoaded=0;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>Number(n||0).toLocaleString('de-DE');
  const pct=n=>n==null?'neu':`${n>0?'+':''}${Math.round(Number(n)||0)} %`;
  const clsDelta=n=>n==null?'':Number(n)>0?'up':Number(n)<0?'down':'';
  const dateTime=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});};
  async function api(){const r=await fetch('/api/admin/insights',{credentials:'same-origin',headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  function set(id,v){const e=$(id);if(e)e.textContent=v;}
  function levelIcon(level){return level==='critical'?'!':level==='warning'?'△':level==='positive'?'✓':'i';}
  function renderInsights(rows=[]){const root=$('insightList');if(!root)return;set('insightCount',`${rows.length} Hinweise`);if(!rows.length){root.innerHTML='<div class="insight-empty">Aktuell gibt es keine besonderen Auffälligkeiten.</div>';return;}root.innerHTML=rows.map(x=>`<article class="insight-row ${esc(x.level)}"><div class="insight-icon">${levelIcon(x.level)}</div><div class="insight-copy"><small>${esc(x.category)}</small><strong>${esc(x.title)}</strong><p>${esc(x.message)}</p><div class="insight-action"><b>EMPFEHLUNG:</b> ${esc(x.action)}</div></div><span class="insight-metric">${esc(x.metric||'')}</span></article>`).join('');}
  function renderTimeline(rows=[]){const root=$('timelineChart');if(!root)return;const max=Math.max(1,...rows.map(x=>Math.max(Number(x.captures)||0,Number(x.bosses)||0)));root.innerHTML=rows.map(x=>{const ch=Math.max(2,(Number(x.captures)||0)/max*155),bh=Math.max(Number(x.bosses)||0?4:2,(Number(x.bosses)||0)/max*155);const d=new Date(`${x.date}T00:00:00`);const label=Number.isNaN(d.getTime())?x.date:d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'});return `<div class="timeline-day" title="${esc(label)} · ${fmt(x.captures)} Fänge · ${fmt(x.bosses)} Bosse"><div class="timeline-bars"><i class="timeline-bar" style="height:${ch}px"></i><i class="timeline-bar boss" style="height:${bh}px"></i></div><span>${esc(label)}</span></div>`;}).join('');}
  function trendRow(label,current,previous,delta){return `<div class="trend-row"><div><span>${esc(label)}</span><strong>${fmt(current)} <small>vs. ${fmt(previous)}</small></strong></div><b class="trend-delta ${clsDelta(delta)}">${esc(pct(delta))}</b></div>`;}
  function renderTrends(d){const root=$('trendGrid');if(!root)return;root.innerHTML=trendRow('AKTIVE SPIELER',d.current.activePlayers,d.previous.activePlayers,d.trends.activePlayers)+trendRow('FÄNGE',d.current.captures,d.previous.captures,d.trends.captures)+trendRow('ALPHA-FÄNGE',d.current.alphas,d.previous.alphas,d.trends.alphas)+trendRow('BOSSE',d.current.bosses,d.previous.bosses,d.trends.bosses);}
  function meter(p){return `<div class="meter-track"><i style="width:${Math.max(0,Math.min(100,Number(p)||0)).toFixed(1)}%"></i></div>`;}
  function renderMissions(m){const root=$('missionInsight');if(!root)return;if(!m){root.innerHTML='<div class="insight-empty">Keine Missionsdaten.</div>';return;}const label=m.difficulty==='hard'?'Eher schwer':m.difficulty==='easy'?'Eher leicht':'Ausgeglichen';root.innerHTML=`<div class="meter-summary"><div><span>MITTLERER FORTSCHRITT</span><strong>${Math.round(m.averageProgress||0)}%</strong></div><b>${esc(label)}</b></div>${meter(m.averageProgress)}<div class="meter-meta"><div><span>TEILNEHMER</span><strong>${fmt(m.participants)}</strong></div><div><span>MISSIONEN ERLEDIGT</span><strong>${Math.round(m.completionRate||0)}%</strong></div><div><span>BELOHNUNGEN ABGEHOLT</span><strong>${fmt(m.claimed)}</strong></div><div><span>WOCHENHELDEN</span><strong>${fmt(m.heroes)}</strong></div></div><div class="meter-note">${Math.round(m.elapsed||0)} % der ${esc(m.week?.label||'Woche')} sind vergangen.</div>`;}
  function renderSeason(s){const root=$('seasonInsight');if(!root)return;if(!s?.available){root.innerHTML='<div class="insight-empty">Noch keine Saison konfiguriert.</div>';return;}const pace=s.pace==='behind'?'Hinter Zeitplan':s.pace==='ahead'?'Vor Zeitplan':s.pace==='on-track'?'Im Zeitplan':s.state==='ended'?'Beendet':s.state==='upcoming'?'Noch nicht gestartet':'Ohne Zeitplan';root.innerHTML=`<div class="meter-summary"><div><span>${esc(s.title||'COMMUNITY-EVENT')}</span><strong>${Math.round(s.progress||0)}%</strong></div><b>${esc(pace)}</b></div>${meter(s.progress)}<div class="meter-meta"><div><span>ENGPASS</span><strong>${esc(s.bottleneck?.label||'—')}</strong></div><div><span>ENGPASS-FORTSCHRITT</span><strong>${Math.round(s.bottleneck?.progress||0)}%</strong></div><div><span>ZEIT VERGANGEN</span><strong>${s.elapsed==null?'—':`${Math.round(s.elapsed)}%`}</strong></div><div><span>TAGE VERBLEIBEND</span><strong>${s.daysRemaining==null?'—':Math.ceil(s.daysRemaining)}</strong></div></div>`;}
  function watchRow(index,name,sub,metric){return `<div class="watch-row"><b>${String(index).padStart(2,'0')}</b><div><strong>${esc(name)}</strong><small>${esc(sub)}</small></div><em>${esc(metric)}</em></div>`;}
  function renderWatch(w){const top=$('topPerformers'),ret=$('returners'),inactive=$('inactivePlayers');if(top)top.innerHTML=w.topPerformers?.length?w.topPerformers.map((x,i)=>{const delta=Number(x.delta||0);const change=delta===0?'unverändert':`${delta>0?'+':''}${fmt(delta)} vs. Vorwoche`;return watchRow(i+1,x.name,`${x.captures} Fänge · ${x.alphas} Alpha · ${x.bosses} Bosse · ${change}`,`${fmt(x.score)} Score`);}).join(''):'<div class="insight-empty">Noch keine 7-Tage-Aktivität.</div>';if(ret){const rows=[...(w.returners||[]).map(x=>({name:x.name,sub:`Nach ${Math.round(x.gapDays)} Tagen Pause zurück`,metric:`${fmt(x.score)} Score`})),...(w.newPlayers||[]).map(x=>({name:x.name,sub:'Erstmals in Gameplay-Daten erfasst',metric:'NEU'}))];ret.innerHTML=rows.length?rows.slice(0,10).map((x,i)=>watchRow(i+1,x.name,x.sub,x.metric)).join(''):'<div class="insight-empty">Keine Rückkehrer oder neuen Spieler erkannt.</div>';}if(inactive)inactive.innerHTML=w.inactive?.length?w.inactive.map((x,i)=>watchRow(i+1,x.name,`Zuletzt gesehen: ${dateTime(x.lastSeen)}`,`${Math.floor(x.daysAway)} Tage`)).join(''):'<div class="insight-empty">Keine länger inaktiven Spieler.</div>';}
  function render(d){set('healthScore',Math.round(d.health?.score||0));set('healthStatus',d.health?.status||'—');set('activePlayers',fmt(d.current?.activePlayers));set('activeTrend',`${pct(d.trends?.activePlayers)} gegenüber vorher`);set('activityEvents',fmt(d.current?.events));set('activityTrend',`${pct(d.trends?.events)} · Fänge + Bosse`);set('attentionCount',fmt(d.health?.attentionCount));set('insightsUpdated',`Stand ${dateTime(d.updatedAt)}`);const health=$('healthScore')?.closest('.health-card');if(health){health.classList.remove('warning','critical');if((d.health?.score||0)<65)health.classList.add('critical');else if((d.health?.score||0)<85)health.classList.add('warning');}renderInsights(d.insights||[]);renderTimeline(d.timeline||[]);renderTrends(d);renderMissions(d.missions);renderSeason(d.season);renderWatch(d.watch||{});}
  async function load(force=false){if(loading)return;if(!force&&Date.now()-lastLoaded<15000)return;if($('adminView')?.classList.contains('hidden'))return;loading=true;try{const d=await api();render(d);lastLoaded=Date.now();}catch(e){if(!/angemeldet/i.test(e.message))window.toast?.(e.message,true);}finally{loading=false;}}
  $('refreshInsights')?.addEventListener('click',()=>load(true));
  setInterval(()=>load(false),900);
})();