(() => {
  const $=id=>document.getElementById(id);let model=null,loading=false;
  async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json'},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function preview(rows=[]){const root=$('missionAdminPreview');if(!root)return;root.innerHTML=rows.length?rows.map(m=>`<article><i>${esc(m.icon)}</i><div><strong>${esc(m.title)}</strong><small>${Number(m.target)} Ziel · ${esc(m.description)}</small></div><b>+${Number(m.reward)}</b></article>`).join(''):'<div class="empty">Keine Missionen.</div>';}
  function ranking(rows=[]){const root=$('missionAdminRanking');if(!root)return;root.innerHTML=rows.length?rows.map((r,i)=>`<a href="/player/${Number(r.userId)}"><b>${String(i+1).padStart(2,'0')}</b><strong>${esc(r.name)}</strong><span>${Number(r.completed||0)}/5</span><em>${Math.round(Number(r.progress||0))}%</em></a>`).join(''):'<div class="empty">Noch keine Wochenaktivität.</div>';}
  function render(data){model=data.config;const c=data.config,current=data.current||{};$('missionEnabled').checked=!!c.enabled;$('targetMultiplier').value=c.targetMultiplier;$('rewardMultiplier').value=c.rewardMultiplier;$('completionBonus').value=c.completionBonus;$('missionAdminWeek').textContent=current.week?.label||'—';$('missionAdminEnabled').textContent=c.enabled?'AKTIV':'PAUSIERT';$('missionAdminParticipants').textContent=Number(current.participantCount??current.leaderboard?.length??0).toLocaleString('de-DE');$('missionAdminBonus').textContent=`${Number(c.completionBonus||0).toLocaleString('de-DE')} P`;$('missionAdminState').textContent='BEREIT';preview(current.missions||[]);ranking(current.leaderboard||[]);}
  function collect(){return {enabled:$('missionEnabled').checked,targetMultiplier:Number($('targetMultiplier').value),rewardMultiplier:Number($('rewardMultiplier').value),completionBonus:Number($('completionBonus').value)};}
  async function load(){if(loading||model||$('adminView')?.classList.contains('hidden'))return;loading=true;$('missionAdminState').textContent='LADE…';try{render(await api('/api/admin/missions'));}catch(e){$('missionAdminState').textContent='FEHLER';}finally{loading=false;}}
  $('saveMissionConfig')?.addEventListener('click',async()=>{const b=$('saveMissionConfig');b.disabled=true;b.textContent='Speichere…';try{render(await api('/api/admin/missions',{method:'POST',body:JSON.stringify({config:collect()})}));b.textContent='Gespeichert ✓';}catch(e){b.textContent='Fehler';}setTimeout(()=>{b.disabled=false;b.textContent='Speichern';},1500);});
  setInterval(load,700);load();
})();