const rr=id=>document.getElementById(id);
let raidOptions=null,raidStatus=null,raidBusy=false,raidOptionsLoading=false;
async function raidReq(url,options={}){const res=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
function raidToast(message,error=false){const node=rr('toast');if(!node)return;node.textContent=message;node.className=`toast show${error?' error':''}`;clearTimeout(raidToast.t);raidToast.t=setTimeout(()=>node.className='toast',3600);}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('de-DE');
function dateTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function stateLabel(state){return({IDLE:'BEREIT',SPAWNING:'SPAWNT',ACTIVE:'AKTIV',REWARDING:'BELOHNUNG',COMPLETED:'BESIEGT',CANCELLED:'ABGEBROCHEN',FAILED:'FEHLER'})[state]||state||'—';}
function isActive(current){return !!current?.active||['SPAWNING','ACTIVE','REWARDING'].includes(current?.state);}
function selectedBoss(){const key=rr('raidSpecies')?.value;return raidOptions?.bosses?.find(x=>x.species===key)||null;}
function numberValue(id,fallback){const n=Number(rr(id)?.value);return Number.isFinite(n)?n:fallback;}
function updatePreview(){if(!raidOptions)return;const d=raidOptions.defaults||{},online=Math.max(1,raidStatus?.onlinePlayers?.length||0),boss=selectedBoss(),base=numberValue('raidBaseLevel',d.baseLevel||35),per=numberValue('raidLevelPerPlayer',d.levelPerPlayer||5),cap=numberValue('raidMaxLevel',d.maxLevel||65),basePower=Number(d.basePower||55),powerPer=Number(d.powerPerPlayer||8),baseScale=numberValue('raidBaseScale',d.baseScale||2.8),scalePer=Number(d.scalePerPlayer||.12),maxScale=Number(d.maxScale||4),level=Math.min(cap,base+Math.max(0,online-1)*per),power=Math.min(100,basePower+Math.max(0,online-1)*powerPer),scale=Math.min(maxScale,baseScale+Math.max(0,online-1)*scalePer);rr('previewBoss').textContent=boss?.name||'—';rr('previewLevel').textContent=`Lv. ${Math.round(level)}`;rr('previewPower').textContent=`Power ${Math.round(power)}`;rr('previewScale').textContent=`${scale.toFixed(2)}× Größe`;rr('previewFormula').textContent=`${raidStatus?.onlinePlayers?.length||0} Spieler online · ${Math.round(base)} Basis + ${Math.round(per)} je weiterem Spieler · Cap ${Math.round(cap)}`;}
function renderRewards(){const root=rr('rewardGrid');if(!root)return;const rows=raidOptions?.rewards||[];root.innerHTML=rows.map(x=>`<div class="reward-item"><span>${esc(x.name||x.item)}</span><strong>${fmt(x.count)}×</strong><small>${esc(x.item)}</small></div>`).join('')||'<div class="raid-empty">Kein Materialpaket konfiguriert.</div>';}
function renderBosses(){const select=rr('raidSpecies');if(!select||!raidOptions)return;const previous=select.value;select.innerHTML=(raidOptions.bosses||[]).map(x=>`<option value="${esc(x.species)}">${esc(x.name)} · ${esc(x.species)}</option>`).join('');if((raidOptions.bosses||[]).some(x=>x.species===previous))select.value=previous;const d=raidOptions.defaults||{};rr('raidBaseLevel').value=d.baseLevel??35;rr('raidLevelPerPlayer').value=d.levelPerPlayer??5;rr('raidMaxLevel').value=d.maxLevel??65;rr('raidBaseScale').value=d.baseScale??2.8;renderRewards();}
function renderPlayers(players=[]){const select=rr('raidAnchor'),previous=select?.value;if(!select)return;select.innerHTML=players.length?players.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}${p.level!=null?` · Stufe ${esc(p.level)}`:''}</option>`).join(''):'<option value="">Keine Online-Spieler</option>';if(players.some(p=>p.name===previous))select.value=previous;}
function participantHtml(rows=[]){if(!rows.length)return'<div class="raid-empty">Noch kein Schaden am Raidboss registriert.</div>';return rows.map((p,i)=>`<div class="raid-player"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${esc(p.name)}</strong><small>${esc(p.itemReward)} Rohstoffe · ${esc(p.palReward)} Pal</small></div><em>${fmt(p.damage)} DMG</em></div>`).join('');}
function renderCurrent(current){const active=isActive(current),live=rr('raidLive'),empty=rr('noRaid');live?.classList.toggle('hidden',!active&&current?.state!=='COMPLETED');empty?.classList.toggle('hidden',active||current?.state==='COMPLETED');rr('currentRaidState').textContent=stateLabel(current?.state);if(!current?.raidId)return;rr('currentBossName').textContent=current.displayName||current.species||'—';rr('currentBossMeta').textContent=`${current.species||'—'} · Power ${Math.round(current.power||0)} · ${Number(current.scale||1).toFixed(2)}× Größe`;rr('currentBossLevel').textContent=Math.round(current.level||0);const loc=current.location||{};rr('currentLocation').textContent=`X ${Math.round(loc.x||0)} · Y ${Math.round(loc.y||0)} · Z ${Math.round(loc.z||0)}`;rr('currentMarkers').textContent=current.markerCount>0?`${current.markerCount} Gruppe${current.markerCount===1?'':'n'}`:'NICHT BESTÄTIGT';rr('currentOnlineStart').textContent=fmt(current.onlineAtStart);rr('currentStarted').textContent=dateTime(current.startedAt);rr('currentParticipantCount').textContent=fmt(current.participantCount);rr('participantList').innerHTML=participantHtml(current.participants||[]);rr('cancelRaidBtn').disabled=!active;}
function renderHistory(rows=[]){const root=rr('raidHistory');if(!root)return;if(!rows.length){root.innerHTML='<div class="raid-empty">Noch keine Raid-Historie.</div>';return;}root.innerHTML=rows.map(x=>`<div class="raid-history-row"><div><strong>${esc(x.displayName||x.species)}</strong><small>${dateTime(x.startedAt)} · ${esc(x.raidId)}</small></div><span>Lv. ${fmt(x.level)}</span><span>${fmt(x.participantCount)} TN</span><b class="raid-history-state ${String(x.state||'').toLowerCase()}">${esc(stateLabel(x.state))}</b></div>`).join('');}
function renderStatus(data){raidStatus=data;const current=data.current||{},active=isActive(current),online=data.onlinePlayers||[],modOk=data.serverMod?.live&&data.serverMod?.raidCapable;renderPlayers(online);rr('raidState').textContent=stateLabel(current.state);rr('raidStateHint').textContent=active?`Raid ${current.raidId||''}`:'Bereit für einen neuen Raid';rr('raidBoss').textContent=current.displayName||'—';rr('raidBossHint').textContent=current.species||'Noch keiner gespawnt';rr('raidLevel').textContent=current.level?`Lv. ${Math.round(current.level)}`:'—';rr('raidPower').textContent=current.level?`Power ${Math.round(current.power||0)} · ${Number(current.scale||1).toFixed(2)}×`:'Level / Power';rr('raidParticipants').textContent=fmt(current.participantCount);rr('raidOnline').textContent=`${online.length} Spieler online`;const pill=rr('raidPill');pill.className=`pill ${active?'online':'offline'}`;rr('raidPillText').textContent=active?`${stateLabel(current.state)} · ${current.displayName||current.species}`:modOk?'Raid-System bereit':'Server-Mod nicht raidfähig';rr('raidModWarning').classList.toggle('hidden',modOk);rr('startRaidBtn').disabled=raidBusy||active||!data.serverRunning||!online.length||!modOk;renderCurrent(current);renderHistory(data.history||[]);updatePreview();}
async function loadOptions(){if(raidOptions||raidOptionsLoading||rr('adminView')?.classList.contains('hidden'))return;raidOptionsLoading=true;try{raidOptions=await raidReq('/api/admin/raids/options');renderBosses();updatePreview();}catch(e){if(!/angemeldet/i.test(e.message))raidToast(e.message,true);}finally{raidOptionsLoading=false;}}
async function refreshRaid(){if(rr('adminView')?.classList.contains('hidden')||raidBusy)return;try{if(!raidOptions)await loadOptions();renderStatus(await raidReq('/api/admin/raids/status'));}catch(e){if(!/angemeldet/i.test(e.message))rr('raidPillText').textContent='Statusfehler';}}
rr('raidSpecies')?.addEventListener('change',updatePreview);['raidBaseLevel','raidLevelPerPlayer','raidMaxLevel','raidBaseScale'].forEach(id=>rr(id)?.addEventListener('input',updatePreview));
rr('raidStartForm')?.addEventListener('submit',async event=>{event.preventDefault();if(raidBusy)return;const boss=selectedBoss(),anchorName=rr('raidAnchor').value,online=raidStatus?.onlinePlayers?.length||0;if(!boss||!anchorName)return raidToast('Boss und Online-Spieler auswählen.',true);updatePreview();if(!confirm(`${boss.name} als Raidboss starten? Aktuell sind ${online} Spieler online. Der Boss wird serverseitig gespawnt und kann während des Raids nicht gefangen werden.`))return;raidBusy=true;rr('startRaidBtn').disabled=true;try{const body={species:boss.species,anchorName,baseLevel:numberValue('raidBaseLevel',35),levelPerPlayer:numberValue('raidLevelPerPlayer',5),maxLevel:numberValue('raidMaxLevel',65),baseScale:numberValue('raidBaseScale',2.8)};const result=await raidReq('/api/admin/raids/start',{method:'POST',body:JSON.stringify(body)});raidToast(`Raid gestartet: ${boss.name} Lv.${result.calculated?.level}.`);}catch(e){raidToast(e.message,true);}finally{raidBusy=false;setTimeout(refreshRaid,600);}});
rr('cancelRaidBtn')?.addEventListener('click',async()=>{if(raidBusy||!isActive(raidStatus?.current))return;if(!confirm(`Aktiven Raid ${raidStatus.current.displayName||raidStatus.current.species} wirklich abbrechen? Es werden keine Sieg-Belohnungen verteilt.`))return;raidBusy=true;try{await raidReq('/api/admin/raids/cancel',{method:'POST',body:'{}'});raidToast('Raid beendet.');}catch(e){raidToast(e.message,true);}finally{raidBusy=false;setTimeout(refreshRaid,500);}});
setTimeout(refreshRaid,500);setInterval(refreshRaid,2000);
