(() => {
  const $=id=>document.getElementById(id); let model=null,loading=false;
  async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json'},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  function dt(v){if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return '';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
  function iso(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString();}
  function set(id,v){if($(id))$(id).value=v??'';}
  function fmt(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'});}
  function render(d){model=d.config;const c=d.config,s=d.snapshot||{};set('seasonId',c.id);set('seasonTitleInput',c.title);set('seasonSubtitleInput',c.subtitle);set('seasonStart',dt(c.startAt));set('seasonEnd',dt(c.endAt));$('seasonActive').checked=!!c.active;set('communityCaptures',c.communityGoals.captures);set('communityUnique',c.communityGoals.uniqueSpecies);set('communityAlpha',c.communityGoals.alphaCaptures);set('communityBosses',c.communityGoals.bosses);set('personalCaptures',c.personalGoals.captures);set('personalUnique',c.personalGoals.uniqueSpecies);set('personalAlpha',c.personalGoals.alphaCaptures);set('personalBosses',c.personalGoals.bosses);$('adminCommunityProgress').textContent=`${Math.round(Number(s.community?.progress||0))}%`;$('adminSeasonStatus').textContent=String(s.season?.state||'—').toUpperCase();$('adminParticipants').textContent=Number(s.community?.participantCount??s.community?.contributors?.length??0).toLocaleString('de-DE');$('adminTopScore').textContent=Number(s.community?.contributors?.[0]?.seasonScore||0).toLocaleString('de-DE');$('adminTopName').textContent=s.community?.contributors?.[0]?.name||'Noch keine Daten';$('seasonAdminState').textContent='BEREIT';const root=$('rewardGrid');root.innerHTML=(c.rewards||[]).map((r,i)=>`<article data-i="${i}"><span>${r.personal?'PERSÖNLICH':'COMMUNITY'} · ${r.threshold}%</span><label>Name<input data-k="label" value="${String(r.label||'').replace(/"/g,'&quot;')}"></label><label>Punkte<input data-k="points" type="number" min="0" value="${Number(r.points||0)}"></label></article>`).join('');}
  function collect(){if(!model)throw new Error('Saisondaten sind noch nicht geladen.');const rewards=(model.rewards||[]).map((r,i)=>{const el=document.querySelector(`[data-i="${i}"]`);return {...r,label:el?.querySelector('[data-k="label"]')?.value||r.label,points:Number(el?.querySelector('[data-k="points"]')?.value||0)};});return {id:$('seasonId').value,title:$('seasonTitleInput').value,subtitle:$('seasonSubtitleInput').value,startAt:iso($('seasonStart').value),endAt:iso($('seasonEnd').value),active:$('seasonActive').checked,communityGoals:{captures:Number($('communityCaptures').value),uniqueSpecies:Number($('communityUnique').value),alphaCaptures:Number($('communityAlpha').value),bosses:Number($('communityBosses').value)},personalGoals:{captures:Number($('personalCaptures').value),uniqueSpecies:Number($('personalUnique').value),alphaCaptures:Number($('personalAlpha').value),bosses:Number($('personalBosses').value)},rewards};}
  async function load(){if(loading||model||$('adminView')?.classList.contains('hidden'))return;loading=true;$('seasonAdminState').textContent='LADE…';try{render(await api('/api/admin/season'));await loadHistory();}catch(e){$('seasonAdminState').textContent='FEHLER';}finally{loading=false;}}
  async function loadHistory(){const root=$('seasonHistoryAdmin');if(!root)return;try{const d=await api('/api/admin/season/history');const rows=d.archives||[];root.innerHTML=rows.length?rows.map(a=>`<article class="season-history-admin-row"><span><strong>${a.title}</strong><small>${fmt(a.startAt)} → ${fmt(a.endAt)}</small></span><span><b>${Math.round(Number(a.communityProgress||0))}%</b><small>Community</small></span><span><b>${Number(a.participantCount||0)}</b><small>Teilnehmer</small></span><a class="btn mini" href="/hall-of-fame">Ansehen</a></article>`).join(''):'<div class="season-history-admin-empty">Noch keine Saison archiviert.</div>';}catch(e){root.innerHTML='<div class="season-history-admin-empty">Archiv konnte nicht geladen werden.</div>';}}
  $('saveSeasonBtn')?.addEventListener('click',async()=>{const b=$('saveSeasonBtn');b.disabled=true;b.textContent='Speichere…';try{render(await api('/api/admin/season',{method:'POST',body:JSON.stringify({config:collect()})}));b.textContent='Gespeichert ✓';}catch(e){b.textContent='Fehler';}setTimeout(()=>{b.disabled=false;b.textContent='Saison speichern';},1600);});
  $('archiveSeasonBtn')?.addEventListener('click',async()=>{const b=$('archiveSeasonBtn');if(!confirm('Diese Saison jetzt einfrieren und dauerhaft in der Hall of Fame archivieren? Danach kann dieselbe Saison-ID nicht erneut archiviert werden.'))return;b.disabled=true;b.textContent='Archiviere…';try{const d=await api('/api/admin/season/archive',{method:'POST',body:'{}'});b.textContent=`Archiviert ✓ (${Number(d.honorsAwarded||0)} Titel)`;await loadHistory();}catch(e){b.textContent=e.message;}setTimeout(()=>{b.disabled=false;b.textContent='Saison archivieren';},2400);});
  setInterval(load,700);load();
})();