const sm=id=>document.getElementById(id);
let lastStatus=null;
async function smReq(url,options={}){const res=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
function smToast(message,error=false){const node=sm('toast');if(!node)return;node.textContent=message;node.className=`toast show${error?' error':''}`;clearTimeout(smToast.t);smToast.t=setTimeout(()=>node.className='toast',3400);}
function age(ms){if(ms==null)return'Noch kein Lebenszeichen';if(ms<1500)return'gerade eben';if(ms<60000)return`vor ${Math.max(1,Math.round(ms/1000))} Sek.`;return`vor ${Math.round(ms/60000)} Min.`;}
function render(data){lastStatus=data;sm('modsUe4ss').textContent=data.ue4ss.ready?'BEREIT':'FEHLT';sm('modsInstalled').textContent=data.mod.installed?(data.mod.updateAvailable?'UPDATE':'INSTALLIERT'):'FEHLT';sm('modsVersion').textContent=data.mod.installedVersion?`Version ${data.mod.installedVersion}`:'Nicht installiert';sm('modsHeartbeat').textContent=data.heartbeat.live?'AKTIV':data.mod.installed?'OFFLINE':'—';sm('modsHeartbeatAge').textContent=age(data.heartbeat.ageMs);sm('modsPlayers').textContent=String((data.players||[]).length);sm('modsSource').textContent=`Quelle ${data.sourceVersion||'—'}`;sm('modsServer').textContent=data.serverRunning?'ONLINE':'GESTOPPT';sm('modsDestination').textContent=data.mod.destination||'—';sm('modsIpc').textContent=data.mod.ipcDir||'—';sm('modsCapabilities').textContent=(data.heartbeat.capabilities?.length?data.heartbeat.capabilities:data.sourceCapabilities||[]).join(', ')||'—';const pill=sm('modsPill');pill.className=`pill ${data.heartbeat.live?'online':'offline'}`;sm('modsPillText').textContent=data.heartbeat.live?'Server-Mod aktiv':data.mod.installed?'Server-Mod offline':'Nicht installiert';sm('installServerMods').disabled=data.serverRunning||!data.ue4ss.ready;sm('uninstallServerMods').disabled=data.serverRunning||!data.mod.installed;sm('pingServerMods').disabled=!data.heartbeat.live;sm('pulseBtn').disabled=!data.heartbeat.live||!(data.players||[]).length;sm('modsRestartHint').textContent=data.mod.installed&&!data.heartbeat.live?'Mod-Dateien sind installiert. Gameserver neu starten, damit UE4SS PalPanelServerMods lädt.':'Installation/Aktualisierung wird beim nächsten Gameserver-Start aktiv.';}
async function refresh(){if(sm('adminView')?.classList.contains('hidden'))return;try{render(await smReq('/api/admin/server-mods/status'));}catch(e){sm('modsPillText').textContent='Statusfehler';}}
sm('installServerMods')?.addEventListener('click',async()=>{if(!confirm('PalPanelServerMods installieren oder aktualisieren? Der Gameserver muss gestoppt sein.'))return;try{const r=await smReq('/api/admin/server-mods/install',{method:'POST',body:'{}'});smToast(`Server-Mod ${r.version} installiert. Gameserver jetzt starten.`);await refresh();}catch(e){smToast(e.message,true);}});
sm('uninstallServerMods')?.addEventListener('click',async()=>{if(!confirm('PalPanelServerMods wirklich entfernen?'))return;try{await smReq('/api/admin/server-mods/uninstall',{method:'POST',body:'{}'});smToast('Server-Mod entfernt.');await refresh();}catch(e){smToast(e.message,true);}});
sm('pingServerMods')?.addEventListener('click',async()=>{try{const r=await smReq('/api/admin/server-mods/ping',{method:'POST',body:'{}'});smToast(`Server-Mod antwortet: ${r.message}`);}catch(e){smToast(e.message,true);}});
sm('pulseForm')?.addEventListener('submit',async event=>{event.preventDefault();const itemId=sm('pulseItem').value.trim(),count=Number(sm('pulseCount').value),message=sm('pulseMessage').value.trim(),box=sm('pulseResult'),players=lastStatus?.players?.length||0;if(!players)return smToast('Mindestens ein Spieler muss online sein.',true);if(!confirm(`Event Pulse starten? ${players} Online-Spieler erhalten jeweils ${count} × ${itemId}.`))return;box.className='servermods-result';box.textContent='Befehl wird direkt an PalPanelServerMods im laufenden PalServer gesendet…';sm('pulseBtn').disabled=true;try{const r=await smReq('/api/admin/server-mods/test-event',{method:'POST',body:JSON.stringify({itemId,count,message})});box.className='servermods-result ok';box.textContent=`✓ Server-Mod aktiv: ${r.delivered} Spieler erhielten ${r.count} × ${r.item}.${r.announced?' Ingame-Ankündigung gesendet.':` Inventar-Test erfolgreich, Announcement fehlgeschlagen: ${r.announcementError||'unbekannt'}`}`;smToast(`Event Pulse erfolgreich: ${r.delivered} Spieler.`);}catch(e){box.className='servermods-result fail';box.textContent=`✕ ${e.message}`;smToast(e.message,true);}finally{setTimeout(refresh,500);}});
setTimeout(refresh,600);setInterval(refresh,3000);
