const fs=require('fs');
const path=require('path');
const http=require('http');
const {DatabaseSync}=require('node:sqlite');

const APP_DIR=path.resolve(__dirname,'..');
const defaults=JSON.parse(fs.readFileSync(path.join(APP_DIR,'config','default.json'),'utf8'));
const DATA_DIR=defaults.paths.data;
const DB_FILE=path.join(DATA_DIR,'palpanel.db');
const MISSION_FILE=path.join(DATA_DIR,'missions.json');
const SEASON_FILE=path.join(DATA_DIR,'season.json');
const CACHE_MS=30000;
let database=null;
let insightCache={at:0,payload:null};
const jsonCache=new Map();
const maintenance={indexes:0,lastCleanupAt:null,expiredSessionsRemoved:0};
let palNames=null;
try{palNames=require(path.join(APP_DIR,'public','pal-names.js'));}catch{}

function db(){if(!database){database=new DatabaseSync(DB_FILE,{timeout:5000});try{database.exec('PRAGMA journal_mode=WAL;');database.exec('PRAGMA busy_timeout=5000;');}catch{}}return database;}
const num=v=>Number(v||0);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
function safeGet(sql,...p){try{return db().prepare(sql).get(...p)||null;}catch{return null;}}
function safeAll(sql,...p){try{return db().prepare(sql).all(...p);}catch{return [];}}
function tableExists(name){return !!safeGet("SELECT 1 AS ok FROM sqlite_master WHERE type='table' AND name=?",name);}
function sendJson(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':data.length,'Cache-Control':'no-store'});res.end(data);}
function validDate(v){const n=Date.parse(v||'');return Number.isFinite(n)?n:null;}
function daysBetween(a,b){return Math.max(0,(Number(b)-Number(a))/86400000);}
function pctChange(current,previous){current=num(current);previous=num(previous);if(previous===0)return current===0?0:null;return(current-previous)/previous*100;}
function loadJsonCached(file,fallback={}){try{const st=fs.statSync(file),old=jsonCache.get(file);if(old&&old.mtime===st.mtimeMs)return old.value;const value=JSON.parse(fs.readFileSync(file,'utf8'));jsonCache.set(file,{mtime:st.mtimeMs,value});return value;}catch{return fallback;}}

async function requireAdmin(req,res){try{const local=loadJsonCached(path.join(DATA_DIR,'config.json'),{});const port=local.panel?.port||defaults.panel?.port||8787;const response=await fetch(`http://127.0.0.1:${port}/api/admin/session`,{headers:{Cookie:String(req.headers.cookie||''),Accept:'application/json'},signal:AbortSignal.timeout(4000)});const body=await response.json().catch(()=>({}));if(!response.ok||!body.authenticated){sendJson(res,401,{error:'Nicht angemeldet.'});return false;}return true;}catch{sendJson(res,401,{error:'Admin-Sitzung konnte nicht geprüft werden.'});return false;}}

function ensureIndexes(){const specs=[
 ['pal_captures','CREATE INDEX IF NOT EXISTS ix_pal_captures_time ON pal_captures(captured_at)'],
 ['pal_captures','CREATE INDEX IF NOT EXISTS ix_pal_captures_user_time ON pal_captures(user_id,captured_at)'],
 ['pal_captures','CREATE INDEX IF NOT EXISTS ix_pal_captures_species_user ON pal_captures(species_key,user_id)'],
 ['boss_completions','CREATE INDEX IF NOT EXISTS ix_boss_time ON boss_completions(completed_at)'],
 ['boss_completions','CREATE INDEX IF NOT EXISTS ix_boss_user_time ON boss_completions(user_id,completed_at)'],
 ['gameplay_events','CREATE INDEX IF NOT EXISTS ix_gameplay_time ON gameplay_events(created_at)'],
 ['gameplay_events','CREATE INDEX IF NOT EXISTS ix_gameplay_user_time ON gameplay_events(user_id,created_at)'],
 ['points_ledger','CREATE INDEX IF NOT EXISTS ix_points_user_time ON points_ledger(user_id,created_at)'],
 ['points_ledger','CREATE INDEX IF NOT EXISTS ix_points_ref_time ON points_ledger(ref_type,created_at)'],
 ['event_score_ledger','CREATE INDEX IF NOT EXISTS ix_event_score_user ON event_score_ledger(user_id)'],
 ['player_links','CREATE INDEX IF NOT EXISTS ix_player_links_seen ON player_links(last_seen_at)'],
 ['user_sessions','CREATE INDEX IF NOT EXISTS ix_user_sessions_expiry ON user_sessions(expires_at)'],
 ['weekly_mission_claims','CREATE INDEX IF NOT EXISTS ix_weekly_claims_week ON weekly_mission_claims(week_key)'],
 ['weekly_mission_titles','CREATE INDEX IF NOT EXISTS ix_weekly_titles_week ON weekly_mission_titles(week_key)'],
 ['season_claims','CREATE INDEX IF NOT EXISTS ix_season_claims_season_user ON season_claims(season_id,user_id)']
 ];let count=0;for(const[table,sql]of specs){if(!tableExists(table))continue;try{db().exec(sql);count++;}catch{}}maintenance.indexes=count;return count;}
function cleanupExpiredSessions(){if(!tableExists('user_sessions'))return 0;try{const result=db().prepare('DELETE FROM user_sessions WHERE expires_at<=?').run(new Date().toISOString());const removed=Number(result.changes||0);maintenance.lastCleanupAt=new Date().toISOString();maintenance.expiredSessionsRemoved+=removed;return removed;}catch{return 0;}}

function namesMap(){const map=new Map();for(const r of safeAll(`SELECT u.id AS userId,COALESCE(NULLIF(l.palworld_name,''),'Entdecker #'||u.id) AS name,l.level AS level,l.last_seen_at AS lastSeen FROM users u LEFT JOIN player_links l ON l.user_id=u.id`))map.set(num(r.userId),{name:r.name||`Entdecker #${r.userId}`,level:r.level,lastSeen:r.lastSeen});return map;}
function infoFor(map,id){return map.get(num(id))||{name:`Entdecker #${id}`,level:null,lastSeen:null};}

function userMetrics(start,end){const map=new Map();const get=id=>{id=num(id);if(!id)return null;if(!map.has(id))map.set(id,{userId:id,captures:0,uniqueSpecies:0,alphas:0,bosses:0,gameplayEvents:0,progressionEvents:0});return map.get(id);};
 for(const r of safeAll(`SELECT user_id AS userId,COUNT(*) AS captures,COUNT(DISTINCT species_key) AS uniqueSpecies,COALESCE(SUM(CASE WHEN is_alpha=1 THEN 1 ELSE 0 END),0) AS alphas FROM pal_captures WHERE captured_at>=? AND captured_at<? GROUP BY user_id`,start,end)){const x=get(r.userId);if(x){x.captures=num(r.captures);x.uniqueSpecies=num(r.uniqueSpecies);x.alphas=num(r.alphas);}}
 for(const r of safeAll('SELECT user_id AS userId,COUNT(*) AS bosses FROM boss_completions WHERE completed_at>=? AND completed_at<? GROUP BY user_id',start,end)){const x=get(r.userId);if(x)x.bosses=num(r.bosses);}
 if(tableExists('gameplay_events'))for(const r of safeAll('SELECT user_id AS userId,COUNT(*) AS n FROM gameplay_events WHERE created_at>=? AND created_at<? GROUP BY user_id',start,end)){const x=get(r.userId);if(x)x.gameplayEvents=num(r.n);}
 if(tableExists('points_ledger'))for(const r of safeAll(`SELECT user_id AS userId,COUNT(*) AS n FROM points_ledger WHERE created_at>=? AND created_at<? AND (ref_type='playtime' OR (ref_type='event_bonus' AND reason LIKE 'Level %')) GROUP BY user_id`,start,end)){const x=get(r.userId);if(x)x.progressionEvents=num(r.n);}
 for(const x of map.values()){x.score=x.captures+x.uniqueSpecies*3+x.alphas*6+x.bosses*12;x.activitySignals=x.captures+x.bosses+x.gameplayEvents+x.progressionEvents;}
 return map;}
function eventMetrics(start,end,users){const cap=safeGet(`SELECT COUNT(*) AS captures,COUNT(DISTINCT species_key) AS uniqueSpecies,COALESCE(SUM(CASE WHEN is_alpha=1 THEN 1 ELSE 0 END),0) AS alphas FROM pal_captures WHERE captured_at>=? AND captured_at<?`,start,end)||{};const boss=safeGet('SELECT COUNT(*) AS bosses FROM boss_completions WHERE completed_at>=? AND completed_at<?',start,end)||{};const gameplay=tableExists('gameplay_events')?num(safeGet('SELECT COUNT(*) AS n FROM gameplay_events WHERE created_at>=? AND created_at<?',start,end)?.n):0;const progression=tableExists('points_ledger')?num(safeGet(`SELECT COUNT(*) AS n FROM points_ledger WHERE created_at>=? AND created_at<? AND (ref_type='playtime' OR (ref_type='event_bonus' AND reason LIKE 'Level %'))`,start,end)?.n):0;return{captures:num(cap.captures),uniqueSpecies:num(cap.uniqueSpecies),alphas:num(cap.alphas),bosses:num(boss.bosses),gameplayEvents:gameplay,progressionEvents:progression,activePlayers:users.size,events:num(cap.captures)+num(boss.bosses)+gameplay+progression};}

function latestActivityMap(before){const pieces=[],params=[];if(tableExists('pal_captures')){pieces.push('SELECT user_id,captured_at AS at FROM pal_captures WHERE captured_at<?');params.push(before);}if(tableExists('boss_completions')){pieces.push('SELECT user_id,completed_at AS at FROM boss_completions WHERE completed_at<?');params.push(before);}if(tableExists('gameplay_events')){pieces.push('SELECT user_id,created_at AS at FROM gameplay_events WHERE created_at<?');params.push(before);}if(tableExists('points_ledger')){pieces.push(`SELECT user_id,created_at AS at FROM points_ledger WHERE created_at<? AND (ref_type='playtime' OR (ref_type='event_bonus' AND reason LIKE 'Level %'))`);params.push(before);}if(!pieces.length)return new Map();const rows=safeAll(`SELECT user_id AS userId,MAX(at) AS at FROM (${pieces.join(' UNION ALL ')}) GROUP BY user_id`,...params);return new Map(rows.map(r=>[num(r.userId),validDate(r.at)]));}
function dailyTimeline(startMs,days=14){const now=Date.now(),end=new Date(now).toISOString(),start=new Date(startMs).toISOString(),buckets=new Map();for(let i=0;i<days;i++){const d=new Date(startMs+i*86400000).toISOString().slice(0,10);buckets.set(d,{date:d,captures:0,alphas:0,bosses:0});}for(const r of safeAll(`SELECT substr(captured_at,1,10) AS day,COUNT(*) AS captures,COALESCE(SUM(CASE WHEN is_alpha=1 THEN 1 ELSE 0 END),0) AS alphas FROM pal_captures WHERE captured_at>=? AND captured_at<? GROUP BY substr(captured_at,1,10)`,start,end)){if(buckets.has(r.day)){const x=buckets.get(r.day);x.captures=num(r.captures);x.alphas=num(r.alphas);}}for(const r of safeAll(`SELECT substr(completed_at,1,10) AS day,COUNT(*) AS bosses FROM boss_completions WHERE completed_at>=? AND completed_at<? GROUP BY substr(completed_at,1,10)`,start,end)){if(buckets.has(r.day))buckets.get(r.day).bosses=num(r.bosses);}return[...buckets.values()].map(x=>({...x,total:x.captures+x.bosses}));}

function isoWeek(date=new Date()){const local=new Date(date.getFullYear(),date.getMonth(),date.getDate()),day=(local.getDay()+6)%7,monday=new Date(local);monday.setDate(local.getDate()-day);monday.setHours(0,0,0,0);const end=new Date(monday);end.setDate(monday.getDate()+7);const thursday=new Date(monday);thursday.setDate(monday.getDate()+3);const first=new Date(thursday.getFullYear(),0,4),fd=(first.getDay()+6)%7;first.setDate(first.getDate()-fd+3);first.setHours(0,0,0,0);const week=1+Math.round((thursday-first)/604800000);return{year:thursday.getFullYear(),week,key:`${thursday.getFullYear()}-W${String(week).padStart(2,'0')}`,label:`KW ${String(week).padStart(2,'0')}`,start:monday.toISOString(),end:end.toISOString(),startMs:monday.getTime(),endMs:end.getTime()};}
const VARIANTS={captures:[['Fangrunde',12],['Große Fangtour',20],['Fangmarathon',30]],uniqueSpecies:[['Paldex-Streifzug',6],['Artenforscher',10],['Paldex-Woche',15]],alphaCaptures:[['Alpha-Kontakt',1],['Alpha-Jagd',3],['Alpha-Elite',5]],bosses:[['Bossprobe',1],['Bossjäger',2],['Bossbrecher',3]],expeditionScore:[['Expeditionsdrang',45],['Große Expedition',80],['Palpagos-Intensiv',130]]};
function missionSet(week,cfg){return Object.keys(VARIANTS).map((metric,i)=>{const[title,base]=VARIANTS[metric][(week.week+i*2)%3];return{metric,title,target:Math.max(1,Math.round(base*(Number(cfg.targetMultiplier)||1)))};});}
function missionAnalysis(nowMs,nameMap){const cfg={enabled:true,targetMultiplier:1,rewardMultiplier:1,completionBonus:250,...loadJsonCached(MISSION_FILE,{})},week=isoWeek(new Date(nowMs)),all=userMetrics(week.start,week.end),users=[...all.values()].filter(x=>x.captures+x.alphas+x.bosses+x.uniqueSpecies>0),missions=missionSet(week,cfg);let completed=0,progressSum=0;const rows=[];for(const x of users){let userCompleted=0,userProgress=0;for(const m of missions){const value=m.metric==='captures'?x.captures:m.metric==='uniqueSpecies'?x.uniqueSpecies:m.metric==='alphaCaptures'?x.alphas:m.metric==='bosses'?x.bosses:x.score,progress=clamp(value/m.target*100,0,100);progressSum+=progress;userProgress+=progress;if(value>=m.target){completed++;userCompleted++;}}rows.push({userId:x.userId,name:infoFor(nameMap,x.userId).name,completed:userCompleted,progress:userProgress/missions.length,score:x.score});}rows.sort((a,b)=>b.completed-a.completed||b.progress-a.progress||b.score-a.score);const participants=users.length,totalSlots=participants*missions.length,avgProgress=totalSlots?progressSum/totalSlots:0,completionRate=totalSlots?completed/totalSlots*100:0,claimed=tableExists('weekly_mission_claims')?num(safeGet('SELECT COUNT(*) AS n FROM weekly_mission_claims WHERE week_key=?',week.key)?.n):0,heroes=tableExists('weekly_mission_titles')?num(safeGet('SELECT COUNT(*) AS n FROM weekly_mission_titles WHERE week_key=?',week.key)?.n):0,elapsed=clamp((nowMs-week.startMs)/(week.endMs-week.startMs)*100,0,100);let difficulty='balanced';if(participants>=2&&elapsed>35&&avgProgress<elapsed*.55)difficulty='hard';else if(participants>=2&&elapsed<78&&avgProgress>Math.min(92,elapsed*1.45+12))difficulty='easy';return{enabled:cfg.enabled!==false,week,participants,missions,averageProgress:avgProgress,completionRate,claimed,heroes,elapsed,difficulty,leaderboard:rows.slice(0,8)};}

function seasonAnalysis(nowMs){const s=loadJsonCached(SEASON_FILE,null);if(!s)return{available:false};const startRaw=s.startAt,endRaw=s.endAt,start=validDate(startRaw),end=validDate(endRaw),dateIssues=[];if(startRaw&&!start)dateIssues.push('Startdatum ungültig');if(endRaw&&!end)dateIssues.push('Enddatum ungültig');if(start&&end&&end<=start)dateIssues.push('Enddatum liegt nicht nach dem Startdatum');const capParts=[],capParams=[],bossParts=[],bossParams=[];if(start){const x=new Date(start).toISOString();capParts.push('captured_at>=?');bossParts.push('completed_at>=?');capParams.push(x);bossParams.push(x);}if(end){const x=new Date(end).toISOString();capParts.push('captured_at<=?');bossParts.push('completed_at<=?');capParams.push(x);bossParams.push(x);}const cap=safeGet(`SELECT COUNT(*) AS captures,COUNT(DISTINCT species_key) AS uniqueSpecies,COALESCE(SUM(CASE WHEN is_alpha=1 THEN 1 ELSE 0 END),0) AS alphas FROM pal_captures${capParts.length?' WHERE '+capParts.join(' AND '):''}`,...capParams)||{},boss=safeGet(`SELECT COUNT(*) AS bosses FROM boss_completions${bossParts.length?' WHERE '+bossParts.join(' AND '):''}`,...bossParams)||{};const values={captures:num(cap.captures),uniqueSpecies:num(cap.uniqueSpecies),alphaCaptures:num(cap.alphas),bosses:num(boss.bosses)},goals=s.communityGoals||{},defs=[['captures','Fänge'],['uniqueSpecies','Pal-Arten'],['alphaCaptures','Alpha-Fänge'],['bosses','Bosse']],rows=defs.map(([key,label])=>{const target=Math.max(1,num(goals[key]));return{key,label,current:values[key],target,progress:clamp(values[key]/target*100,0,100)};}),progress=rows.length?Math.min(...rows.map(r=>r.progress)):0,bottleneck=[...rows].sort((a,b)=>a.progress-b.progress)[0]||null;let elapsed=null,daysRemaining=null,pace='unknown';if(start&&end&&end>start){elapsed=clamp((nowMs-start)/(end-start)*100,0,100);daysRemaining=Math.max(0,(end-nowMs)/86400000);if(progress+15<elapsed)pace='behind';else if(progress>elapsed+10)pace='ahead';else pace='on-track';}const state=s.active===false?'inactive':start&&nowMs<start?'upcoming':end&&nowMs>end?'ended':'active';return{available:true,id:s.id||'',title:s.title||'Community-Event',state,progress,elapsed,daysRemaining,pace,bottleneck,goals:rows,dateIssues};}

function playerWatch(currentStart,currentEnd,currentUsers,previousUsers,nameMap){const now=Date.parse(currentEnd),latest=latestActivityMap(currentEnd),prior=latestActivityMap(currentStart),linked=safeAll('SELECT user_id AS userId,palworld_name AS name,level,last_seen_at AS lastSeen FROM player_links'),inactive=[],neverSeen=[];for(const r of linked){const id=num(r.userId),seen=Math.max(validDate(r.lastSeen)||0,latest.get(id)||0);if(!seen){neverSeen.push({userId:id,name:r.name||`Entdecker #${id}`});continue;}const daysAway=daysBetween(seen,now);if(daysAway>=7)inactive.push({...r,userId:id,name:r.name||`Entdecker #${id}`,lastSeen:new Date(seen).toISOString(),daysAway});}inactive.sort((a,b)=>b.daysAway-a.daysAway);const inactive14=inactive.filter(r=>r.daysAway>=14).length,returners=[],newPlayers=[];for(const x of currentUsers.values()){const before=prior.get(x.userId)||0,info=infoFor(nameMap,x.userId);if(!before)newPlayers.push({userId:x.userId,name:info.name,score:x.score});else{const gap=daysBetween(before,Date.parse(currentStart));if(gap>=7)returners.push({userId:x.userId,name:info.name,gapDays:gap,score:x.score});}}const top=[];let totalScore=0;for(const x of currentUsers.values()){const prev=previousUsers.get(x.userId),info=infoFor(nameMap,x.userId);totalScore+=x.score;top.push({userId:x.userId,name:info.name,score:x.score,previousScore:prev?.score||0,delta:x.score-(prev?.score||0),captures:x.captures,alphas:x.alphas,bosses:x.bosses,activitySignals:x.activitySignals});}top.sort((a,b)=>b.score-a.score||b.activitySignals-a.activitySignals||b.delta-a.delta);return{linkedPlayers:linked.length,inactiveCount:inactive.length,inactive14Count:inactive14,inactive:inactive.slice(0,10),neverSeenCount:neverSeen.length,returners:returners.slice(0,8),newPlayers:newPlayers.slice(0,8),topPerformers:top.slice(0,8),topShare:totalScore>0&&top[0]?top[0].score/totalScore*100:0,totalScore};}

function dataQuality(season,watch){const issues=[];let score=100;const captureBad=tableExists('pal_captures')?num(safeGet("SELECT COUNT(*) AS n FROM pal_captures WHERE captured_at IS NULL OR julianday(captured_at) IS NULL")?.n):0,bossBad=tableExists('boss_completions')?num(safeGet("SELECT COUNT(*) AS n FROM boss_completions WHERE completed_at IS NULL OR julianday(completed_at) IS NULL")?.n):0,orphanCaptures=tableExists('pal_captures')?num(safeGet('SELECT COUNT(*) AS n FROM pal_captures c WHERE NOT EXISTS(SELECT 1 FROM users u WHERE u.id=c.user_id)')?.n):0,orphanBosses=tableExists('boss_completions')?num(safeGet('SELECT COUNT(*) AS n FROM boss_completions b WHERE NOT EXISTS(SELECT 1 FROM users u WHERE u.id=b.user_id)')?.n):0;if(captureBad+bossBad){issues.push({level:'warning',label:'Ungültige Zeitstempel',value:captureBad+bossBad});score-=20;}if(orphanCaptures+orphanBosses){issues.push({level:'warning',label:'Verwaiste Gameplay-Datensätze',value:orphanCaptures+orphanBosses});score-=15;}let unknown=[];if(palNames?.names&&tableExists('pal_captures')){unknown=safeAll('SELECT DISTINCT species_key AS key FROM pal_captures WHERE species_key IS NOT NULL').map(r=>String(r.key||'')).filter(key=>key&&!palNames.names[key]&&!palNames.names[key.replace(/^(?:BOSS_|Boss_)/,'')]);if(unknown.length){issues.push({level:'info',label:'Noch unbekannte Pal-IDs',value:unknown.length});score-=Math.min(8,unknown.length);}}if(season?.dateIssues?.length){issues.push({level:'warning',label:'Saison-Datumsproblem',value:season.dateIssues.length});score-=15;}if(watch?.neverSeenCount){issues.push({level:'info',label:'Verknüpft, aber noch nie gesehen',value:watch.neverSeenCount});score-=Math.min(5,watch.neverSeenCount);}return{score:clamp(score,0,100),status:score>=90?'SAUBER':score>=70?'PRÜFEN':'AUFRÄUMEN',issues,unknownSpecies:unknown.slice(0,6),orphanRecords:orphanCaptures+orphanBosses,invalidTimestamps:captureBad+bossBad};}

function buildPayload(){ensureIndexes();const nowMs=Date.now(),nowIso=new Date(nowMs).toISOString(),currentStart=new Date(nowMs-7*86400000).toISOString(),previousStart=new Date(nowMs-14*86400000).toISOString(),nameMap=namesMap(),currentUsers=userMetrics(currentStart,nowIso),previousUsers=userMetrics(previousStart,currentStart),current=eventMetrics(currentStart,nowIso,currentUsers),previous=eventMetrics(previousStart,currentStart,previousUsers),missions=missionAnalysis(nowMs,nameMap),season=seasonAnalysis(nowMs),watch=playerWatch(currentStart,nowIso,currentUsers,previousUsers,nameMap),timeline=dailyTimeline(nowMs-13*86400000,14),trends={activePlayers:pctChange(current.activePlayers,previous.activePlayers),captures:pctChange(current.captures,previous.captures),alphas:pctChange(current.alphas,previous.alphas),bosses:pctChange(current.bosses,previous.bosses),events:pctChange(current.events,previous.events)},insights=[];const add=(level,category,title,message,action,metric)=>insights.push({level,category,title,message,action,metric});
 if(previous.activePlayers>=3&&current.activePlayers<=previous.activePlayers*.5)add('critical','Aktivität','Aktive Community deutlich eingebrochen',`Nur ${current.activePlayers} Spieler erzeugten in den letzten sieben Tagen Aktivität; zuvor waren es ${previous.activePlayers}.`,'Plane kurzfristig ein gemeinsames Event oder sprich zuletzt aktive Spieler gezielt an.',`${Math.round(trends.activePlayers||0)} %`);else if(previous.activePlayers>=3&&current.activePlayers<previous.activePlayers*.7)add('warning','Aktivität','Aktivität geht zurück',`${current.activePlayers} aktive Spieler gegenüber ${previous.activePlayers} im Vergleichszeitraum.`,'Ein kleiner Community-Anreiz oder ein angekündigter Abend kann den Rückgang früh abfangen.',`${Math.round(trends.activePlayers||0)} %`);else if(current.activePlayers>=3&&trends.activePlayers!=null&&trends.activePlayers>=30)add('positive','Aktivität','Mehr Spieler sind aktiv',`Die Zahl aktiver Spieler ist von ${previous.activePlayers} auf ${current.activePlayers} gestiegen.`,'Nutze den Aufschwung für ein gemeinsames Ziel oder eine neue Challenge.',`+${Math.round(trends.activePlayers)} %`);
 if(previous.captures>=10&&current.captures<previous.captures*.6)add('warning','Gameplay','Fangaktivität sinkt',`In sieben Tagen wurden ${current.captures} Pals gefangen; zuvor waren es ${previous.captures}.`,'Eine Sammel-Challenge oder ein Paldex-Ziel würde genau diesen Bereich wieder anstoßen.',`${Math.round(trends.captures||0)} %`);if(previous.alphas>=3&&current.alphas<previous.alphas*.5)add('warning','Gameplay','Alpha-Jagd verliert Tempo',`${current.alphas} Alpha-Fänge gegenüber ${previous.alphas} im vorherigen Zeitraum.`,'Starte eine Alpha-Jagd oder erhöhe temporär den Alpha-Anreiz bei den Wochenmissionen.',`${Math.round(trends.alphas||0)} %`);if(previous.bosses>=3&&current.bosses<previous.bosses*.5)add('warning','Gameplay','Boss-Aktivität ist eingebrochen',`${current.bosses} Boss-Abschlüsse gegenüber ${previous.bosses} in den sieben Tagen davor.`,'Ein gemeinsamer Bossabend oder eine Boss-Wochenmission wäre aktuell sinnvoll.',`${Math.round(trends.bosses||0)} %`);
 if(missions.participants>=2&&missions.difficulty==='hard')add('warning','Missionen','Wochenmissionen wirken zu schwer',`Die Woche ist zu ${Math.round(missions.elapsed)} % vorbei, der mittlere Missionsfortschritt liegt aber erst bei ${Math.round(missions.averageProgress)} %.`,'Senke den Ziel-Multiplikator leicht oder beobachte noch einen Tag.',`${Math.round(missions.averageProgress)} % Fortschritt`);else if(missions.participants>=2&&missions.difficulty==='easy')add('info','Missionen','Wochenmissionen werden sehr schnell erledigt',`Bei ${Math.round(missions.elapsed)} % vergangener Woche liegt der mittlere Fortschritt bereits bei ${Math.round(missions.averageProgress)} %.`,'Wenn du längere Motivation willst, erhöhe den Ziel-Multiplikator für die nächste Woche leicht.',`${Math.round(missions.completionRate)} % abgeschlossen`);else if(missions.participants>=2)add('positive','Missionen','Wochenmissionen liegen im gesunden Bereich',`${missions.participants} Teilnehmer kommen im Mittel auf ${Math.round(missions.averageProgress)} % Fortschritt.`,'Keine Anpassung nötig; die aktuelle Schwierigkeit wirkt passend.',`${Math.round(missions.averageProgress)} %`);
 if(season.available&&season.state==='active'&&season.pace==='behind')add('warning','Saison','Community-Saison liegt hinter dem Zeitplan',`Der schwächste Zielbereich steht bei ${Math.round(season.progress)} %, während bereits ${Math.round(season.elapsed)} % der Saisonzeit vergangen sind. Engpass: ${season.bottleneck?.label||'—'}.`,'Plane ein Event gezielt für den Engpass oder passe das betroffene Community-Ziel an.',`${Math.round(season.progress)} %`);else if(season.available&&season.state==='active'&&season.pace==='ahead')add('positive','Saison','Saison liegt vor dem Zeitplan',`Community-Fortschritt ${Math.round(season.progress)} % bei ${Math.round(season.elapsed)} % vergangener Zeit.`,'Du kannst die aktuelle Pace beibehalten oder für den Endspurt ein Bonusziel vorbereiten.',`${Math.round(season.progress)} %`);
 if(watch.linkedPlayers>=4&&watch.inactive14Count/watch.linkedPlayers>=.3)add('warning','Bindung','Viele verknüpfte Spieler sind länger inaktiv',`${watch.inactive14Count} von ${watch.linkedPlayers} verbundenen Spielern wurden seit mindestens 14 Tagen nicht gesehen.`,'Ein Rückkehrer-Event oder eine kurze Community-Ankündigung könnte verlorene Spieler reaktivieren.',`${Math.round(watch.inactive14Count/watch.linkedPlayers*100)} %`);if(watch.returners.length)add('positive','Bindung','Rückkehrer sind wieder aktiv',`${watch.returners.length} Spieler haben nach mindestens einer Woche Aktivitätspause wieder Gameplay erzeugt.`,'Nutze den Moment: Rückkehrer reagieren oft gut auf klare aktuelle Ziele und Gruppenaktivitäten.',`${watch.returners.length} Rückkehrer`);if(watch.newPlayers.length)add('info','Community','Neue Spieleraktivität erkannt',`${watch.newPlayers.length} Spieler tauchen erstmals in den erfassten Gameplay-Ereignissen auf.`,'Prüfe, ob Einstieg, Regeln und aktuelle Ziele für Neulinge gut sichtbar sind.',`${watch.newPlayers.length} neu`);if(watch.topPerformers.length>=4&&watch.topShare>=45)add('info','Wettbewerb','Aktivität konzentriert sich stark auf einen Spieler',`${watch.topPerformers[0].name} erzeugt rund ${Math.round(watch.topShare)} % des gewichteten 7-Tage-Aktivitätsscores.`,'Neben Ranglisten auch kooperative Ziele betonen, damit die Motivation breiter verteilt bleibt.',`${Math.round(watch.topShare)} % Anteil`);if(current.events<8)add('info','Datenbasis','Noch wenig Daten für starke Trend-Aussagen',`In den letzten sieben Tagen liegen nur ${current.events} relevante Aktivitätssignale vor.`,'Trends als Hinweis lesen und nach mehr Spielaktivität erneut prüfen.',`${current.events} Signale`);
 const priority={critical:0,warning:1,info:2,positive:3};insights.sort((a,b)=>priority[a.level]-priority[b.level]);let score=100;for(const i of insights){if(i.level==='critical')score-=24;else if(i.level==='warning')score-=11;}score=clamp(score,0,100);const attentionCount=insights.filter(i=>i.level==='critical'||i.level==='warning').length,status=score>=85?'STABIL':score>=65?'BEOBACHTEN':'HANDLUNGSBEDARF',quality=dataQuality(season,watch);return{version:'0.9.12',updatedAt:nowIso,cacheSeconds:Math.round(CACHE_MS/1000),window:{currentStart,currentEnd:nowIso,previousStart,previousEnd:currentStart},health:{score,status,attentionCount},current,previous,trends,timeline,missions,season,watch,insights,dataQuality:quality,maintenance:{...maintenance}};}
function getPayload(force=false){const now=Date.now();if(!force&&insightCache.payload&&now-insightCache.at<CACHE_MS)return insightCache.payload;const payload=buildPayload();insightCache={at:now,payload};return payload;}

const previousCreateServer=http.createServer.bind(http);
http.createServer=function hardeningCreateServer(options,requestListener){const hasOptions=typeof options!=='function',listener=hasOptions?requestListener:options;const wrapped=async(req,res)=>{let url;try{url=new URL(req.url,'http://localhost');}catch{return listener(req,res);}try{if(req.method==='GET'&&url.pathname==='/api/admin/insights-v2'){if(!await requireAdmin(req,res))return;return sendJson(res,200,getPayload(url.searchParams.get('refresh')==='1'));}if(req.method==='GET'&&url.pathname==='/api/admin/maintenance-status'){if(!await requireAdmin(req,res))return;ensureIndexes();return sendJson(res,200,{version:'0.9.12',maintenance:{...maintenance},dataQuality:getPayload(false).dataQuality});}}catch(err){console.warn('[Hardening]',err.message);if(!res.headersSent)return sendJson(res,500,{error:`Konsolidierungsprüfung fehlgeschlagen: ${err.message}`});}return listener(req,res);};return hasOptions?previousCreateServer(options,wrapped):previousCreateServer(wrapped);};

console.log('PalPanel v0.9.12 Konsolidierung + Datenqualitaet geladen.');
require('./server-v0911.js');
setTimeout(()=>{try{ensureIndexes();const removed=cleanupExpiredSessions();console.log(`[Maintenance] ${maintenance.indexes} Performance-Indizes aktiv${removed?` · ${removed} abgelaufene Session(s) entfernt`:''}.`);}catch(err){console.warn('[Maintenance]',err.message);}},1200);
const cleanupTimer=setInterval(()=>{cleanupExpiredSessions();insightCache={at:0,payload:null};},3600000);cleanupTimer.unref?.();
