const fs=require('fs');
const path=require('path');
const http=require('http');
const crypto=require('crypto');

const APP_DIR=path.resolve(__dirname,'..');
const defaults=JSON.parse(fs.readFileSync(path.join(APP_DIR,'config','default.json'),'utf8'));
const DATA_DIR=defaults.paths.data;
const USER_CONFIG=path.join(DATA_DIR,'config.json');
const REST_FILE=path.join(DATA_DIR,'palworld-rest.json');
const SOURCE_DIR=path.join(APP_DIR,'bridge','PalPanelServerMods');
const SOURCE_MANIFEST=path.join(SOURCE_DIR,'manifest.json');

function loadJson(file,fallback=null){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
function config(){const current=loadJson(USER_CONFIG,{})||{},p=current.palworld||{};return{...defaults,...current,panel:{...defaults.panel,...(current.panel||{})},paths:{...defaults.paths,...(current.paths||{})},palworld:{...defaults.palworld,...p,rest:{...defaults.palworld.rest,...(p.rest||{})}}};}
function sendJson(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':data.length,'Cache-Control':'no-store'});res.end(data);}
function readBody(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>65536)reject(new Error('Request too large'));});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch(e){reject(e);}});req.on('error',reject);});}
function parseKv(raw){const out={};String(raw||'').split(/\r?\n/).forEach(line=>{const i=line.indexOf('=');if(i<1)return;const k=line.slice(0,i),v=line.slice(i+1);try{out[k]=decodeURIComponent(v.replace(/\+/g,'%20'));}catch{out[k]=v;}});return out;}
const enc=v=>encodeURIComponent(String(v??''));

async function internal(req,pathname,timeout=4000){const cfg=config();const response=await fetch(`http://127.0.0.1:${cfg.panel.port||8787}${pathname}`,{headers:{Cookie:String(req.headers.cookie||''),Accept:'application/json'},signal:AbortSignal.timeout(timeout)});const body=await response.json().catch(()=>({}));return{response,body};}
async function requireAdmin(req,res){try{const x=await internal(req,'/api/admin/session');if(!x.response.ok||!x.body.authenticated){sendJson(res,401,{error:'Nicht angemeldet.'});return false;}return true;}catch(e){sendJson(res,503,{error:`Admin-Session konnte nicht geprüft werden: ${e.message}`});return false;}}
async function coreStatus(req){const x=await internal(req,'/api/admin/status',5000);if(!x.response.ok)throw new Error(x.body.error||`Admin status HTTP ${x.response.status}`);return x.body;}

function modPaths(){const cfg=config(),win64=path.join(cfg.paths.server,'Pal','Binaries','Win64'),nested=path.join(win64,'ue4ss'),root=fs.existsSync(path.join(nested,'UE4SS.dll'))||!fs.existsSync(path.join(win64,'UE4SS.dll'))?nested:win64;return{win64,root,ue4ssDll:path.join(root,'UE4SS.dll'),proxyDll:path.join(win64,'dwmapi.dll'),memberLayout:path.join(root,'MemberVariableLayout.ini'),modsDir:path.join(root,'Mods'),modDir:path.join(root,'Mods','PalPanelServerMods'),ipcDir:path.join(cfg.paths.data,'bridge-ipc','server-mods')};}
function sourceManifest(){return loadJson(SOURCE_MANIFEST,{version:'0.0.0',capabilities:[]});}
function installedManifest(){return loadJson(path.join(modPaths().modDir,'manifest.json'),null);}
function ensureModsTxt(modsDir,enabled){fs.mkdirSync(modsDir,{recursive:true});const file=path.join(modsDir,'mods.txt');let text='';try{text=fs.readFileSync(file,'utf8');}catch{}const re=/^[ \t]*PalPanelServerMods\s*:\s*[01][ \t]*\r?$/gmi;if(enabled){if(re.test(text)){re.lastIndex=0;text=text.replace(re,'PalPanelServerMods : 1');}else{text+=(text&&!/\r?\n$/.test(text)?'\r\n':'')+'PalPanelServerMods : 1\r\n';}}else{text=text.replace(re,'').replace(/\r?\n{3,}/g,'\r\n\r\n');}fs.writeFileSync(file,text,'utf8');}
function runtimeReady(){const p=modPaths();return fs.existsSync(p.ue4ssDll)&&fs.existsSync(p.proxyDll)&&fs.existsSync(p.memberLayout);}
function heartbeat(){const p=modPaths(),file=path.join(p.ipcDir,'heartbeat.txt');let data=null,ageMs=null;if(fs.existsSync(file)){try{data=parseKv(fs.readFileSync(file,'utf8'));ageMs=Date.now()-fs.statSync(file).mtimeMs;}catch{}}return{live:ageMs!=null&&ageMs<7000,ageMs,version:data?.version||null,state:data?.state||null,capabilities:String(data?.capabilities||'').split(',').filter(Boolean),clientInstallRequired:data?.client_install_required!=='0'};}
function statusPayload(core=null){const p=modPaths(),source=sourceManifest(),installed=installedManifest(),installedOk=!!installed&&fs.existsSync(path.join(p.modDir,'Scripts','main.lua')),hb=heartbeat();return{version:'0.9.13',sourceVersion:source.version,sourceCapabilities:source.capabilities||[],ue4ss:{ready:runtimeReady(),root:p.root,dll:p.ue4ssDll,proxy:p.proxyDll,memberLayout:p.memberLayout},mod:{installed:installedOk,installedVersion:installed?.version||null,updateAvailable:installedOk&&installed?.version!==source.version,destination:p.modDir,ipcDir:p.ipcDir},heartbeat:{...hb,live:installedOk&&hb.live},serverRunning:!!core?.server?.running,players:(core?.live?.players||[]).map(x=>({name:x.name||'',level:x.level??null,userId:x.userId||''})).filter(x=>x.name)};}
function installMod(){const p=modPaths(),source=sourceManifest();if(!fs.existsSync(SOURCE_MANIFEST))throw new Error('PalPanelServerMods-Paket fehlt im App-Verzeichnis.');if(!runtimeReady())throw new Error(`Palworld-UE4SS ist nicht vollständig erkannt. Erwartet: ${p.ue4ssDll}, ${p.proxyDll} und ${p.memberLayout}`);fs.mkdirSync(p.modsDir,{recursive:true});fs.mkdirSync(p.ipcDir,{recursive:true});fs.mkdirSync(path.join(p.ipcDir,'processed'),{recursive:true});fs.rmSync(p.modDir,{recursive:true,force:true});fs.cpSync(SOURCE_DIR,p.modDir,{recursive:true});fs.writeFileSync(path.join(p.modDir,'ipc_path.txt'),`${p.ipcDir}\r\n`,'utf8');ensureModsTxt(p.modsDir,true);for(const n of ['command.txt','response.txt','heartbeat.txt'])try{fs.rmSync(path.join(p.ipcDir,n),{force:true});}catch{}return{ok:true,version:source.version,destination:p.modDir,restartRequired:true};}
function uninstallMod(){const p=modPaths();fs.rmSync(p.modDir,{recursive:true,force:true});ensureModsTxt(p.modsDir,false);for(const n of ['command.txt','response.txt','heartbeat.txt'])try{fs.rmSync(path.join(p.ipcDir,n),{force:true});}catch{}return{ok:true,restartRequired:true};}

async function sendCommand(type,params={},timeoutMs=10000){const p=modPaths(),s=statusPayload();if(!s.mod.installed)throw new Error('PalPanelServerMods ist nicht installiert.');if(!s.heartbeat.live)throw new Error('PalPanelServerMods ist nicht live. Gameserver nach Installation neu starten.');const commandPath=path.join(p.ipcDir,'command.txt'),responsePath=path.join(p.ipcDir,'response.txt');fs.mkdirSync(p.ipcDir,{recursive:true});if(fs.existsSync(commandPath))throw new Error('Server-Mod ist beschäftigt. Bitte erneut versuchen.');const id=crypto.randomUUID();try{fs.rmSync(responsePath,{force:true});}catch{}const lines=[`id=${enc(id)}`,`type=${enc(type)}`];for(const[k,v]of Object.entries(params))lines.push(`${k}=${enc(v)}`);const tmp=`${commandPath}.tmp`;fs.writeFileSync(tmp,`${lines.join('\n')}\n`,'utf8');fs.renameSync(tmp,commandPath);const started=Date.now();while(Date.now()-started<timeoutMs){await new Promise(r=>setTimeout(r,100));if(!fs.existsSync(responsePath))continue;let reply;try{reply=parseKv(fs.readFileSync(responsePath,'utf8'));}catch{continue;}if(reply.id!==id)continue;try{fs.rmSync(responsePath,{force:true});}catch{}return{id,ok:reply.ok==='1',message:reply.message||'',delivered:Number(reply.delivered||0),failed:Number(reply.failed||0),item:reply.item||null,count:Number(reply.count||0)};}throw new Error('Server-Mod-Timeout: keine Antwort vom Gameserver.');}

async function announce(message){const cfg=config(),creds=loadJson(REST_FILE,null);if(!creds?.password)throw new Error('Palworld REST API ist nicht eingerichtet.');const auth=Buffer.from(`${creds.username||cfg.palworld.rest.username||'admin'}:${creds.password}`).toString('base64');const response=await fetch(`http://${cfg.palworld.rest.host||'127.0.0.1'}:${cfg.palworld.rest.port||8212}/v1/api/announce`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Basic ${auth}`},body:JSON.stringify({message}),signal:AbortSignal.timeout(4000)});if(!response.ok)throw new Error(`Announcement HTTP ${response.status}`);return true;}

const previousCreateServer=http.createServer.bind(http);
http.createServer=function serverModsCreateServer(options,requestListener){const hasOptions=typeof options!=='function',listener=hasOptions?requestListener:options;const wrapped=async(req,res)=>{let url;try{url=new URL(req.url,'http://localhost');}catch{return listener(req,res);}try{
 if((req.method==='GET'||req.method==='HEAD')&&url.pathname==='/admin/server-mods.html'){res.writeHead(308,{Location:`/admin/server-mods${url.search}`,'Cache-Control':'no-store'});return res.end();}
 if((req.method==='GET'||req.method==='HEAD')&&url.pathname==='/admin/server-mods'){req.url=`/admin/server-mods.html${url.search}`;return listener(req,res);}
 if(!url.pathname.startsWith('/api/admin/server-mods'))return listener(req,res);
 if(!await requireAdmin(req,res))return;
 if(req.method==='GET'&&url.pathname==='/api/admin/server-mods/status'){const core=await coreStatus(req);return sendJson(res,200,statusPayload(core));}
 if(req.method==='POST'&&url.pathname==='/api/admin/server-mods/install'){const core=await coreStatus(req);if(core.server?.running)return sendJson(res,409,{error:'Gameserver vor Installation oder Aktualisierung stoppen.'});return sendJson(res,200,installMod());}
 if(req.method==='POST'&&url.pathname==='/api/admin/server-mods/uninstall'){const core=await coreStatus(req);if(core.server?.running)return sendJson(res,409,{error:'Gameserver vor Deinstallation stoppen.'});return sendJson(res,200,uninstallMod());}
 if(req.method==='POST'&&url.pathname==='/api/admin/server-mods/ping'){const result=await sendCommand('ping');return sendJson(res,result.ok?200:502,result.ok?result:{error:result.message,...result});}
 if(req.method==='POST'&&url.pathname==='/api/admin/server-mods/test-event'){const core=await coreStatus(req),players=core.live?.players||[];if(!core.server?.running)return sendJson(res,409,{error:'Gameserver läuft nicht.'});if(!players.length)return sendJson(res,409,{error:'Für den sichtbaren PoC muss mindestens ein Spieler online sein.'});const input=await readBody(req),item=String(input.itemId||'PalSphere').trim(),count=Math.trunc(Number(input.count||1)),message=String(input.message||'PalPanel Testevent: Server-Pulse erfolgreich!').trim().slice(0,180);if(!/^[A-Za-z0-9_]+$/.test(item))return sendJson(res,400,{error:'Ungültige Item-ID.'});if(!Number.isInteger(count)||count<1||count>20)return sendJson(res,400,{error:'Menge muss zwischen 1 und 20 liegen.'});const result=await sendCommand('event_pulse',{item,count});if(!result.ok)return sendJson(res,502,{error:result.message,...result});let announced=false,announcementError=null;try{await announce(message);announced=true;}catch(e){announcementError=e.message;}return sendJson(res,200,{ok:true,...result,announced,announcementError,onlinePlayers:players.length,clientInstallRequired:false});}
 return sendJson(res,404,{error:'Server-Mod route not found'});
 }catch(err){console.error('[PalPanelServerMods]',err);if(!res.headersSent)return sendJson(res,500,{error:err.message||'Server-Mod Fehler'});try{res.end();}catch{}}};return hasOptions?previousCreateServer(options,wrapped):previousCreateServer(wrapped);};

console.log(`PalPanel v0.9.13 Server-Mods geladen. Source: ${sourceManifest().version}`);
console.log(`Server-Mods: ${modPaths().modDir}`);
require('./server-v0912.js');
